name: Deploy to Neocities
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Remove non-site files
        run: rm -rf .git .github && find . -name ".DS_Store" -delete

      - uses: bcomnes/deploy-to-neocities@v2
        with:
          api_token: ${{ secrets.NEOCITIES_API_KEY }}
          dist_dir: .
          cleanup: false
